# --
# Copyright (c) 2008-2024 Net-ng.
# All rights reserved.
#
# This software is licensed under the BSD License, as described in
# the file LICENSE.txt, which you should have received as part of
# this distribution.
# --

image: docker-registry.net-ng.com/nng/dind-stackless:13

tests:
  script:
    - /opt/stackless3/bin/pip install ruff black pytest .
    - /opt/stackless3/bin/ruff check src
    - /opt/stackless3/bin/black src
    - /opt/stackless3/bin/pytest

pages:
  stage: deploy
  script:
    - /opt/stackless3/bin/pip install -e '.[doc]'
    # - /opt/stackless3/bin/sphinx-apidoc -s txt -T -o doc/source nagare
    - /opt/stackless3/bin/sphinx-build -b html doc public
  artifacts:
    paths:
      - public
  only:
    - master
  when: manual

gh-pages:
  script:
    - /opt/stackless3/bin/pip install -e '.[doc]'
    # - /opt/stackless/bin/sphinx-apidoc -s txt -T -o doc/source nagare
    - git clone --branch gh-pages git@git.net-ng.com:nng/nagare-core.git gh-pages
    - /opt/stackless3/bin/sphinx-build -b html doc gh-pages
    - git config --global user.email "alain.poirier@net-ng.com"
    - git config --global user.name "Alain Poirier"
    - msg=`git log master -1 --pretty=short --abbrev-commit`; cd gh-pages; git add .; git commit -m "$msg"
    - git push git@git.net-ng.com:nng/nagare-core.git gh-pages
  when: manual
